### PR TITLE
Adding Cumulative xPts to view

### PR DESCRIPTION
**Pull request by edwardstjohn**

### CODE REVIEW

**Comment by sertalpbilal** [comment]
Hi @edwardstjohn thanks for the pull request. I see that cumulative xPts is being printed after every GW. Is it intentional or do you just want to print it once at the end of the horizon?

**Comment by edwardstjohn** [comment]
Hey @sertalpbilal, yeah that was intentional for me as it was useful seeing the printout each gw to compare different horizons if needed, but equally a single print at the end of the run could also be the better option! Suppose it depends what is more useful for people, I could look into adding a new argument in the settings json to switch between the two perhaps

**Comment by sertalpbilal** [comment]
I see. Would you mind making it a single print at the end? I am a bit afraid that it will be confusing to see cumulative xPts after every GW for a casual user.
Perhaps at another time, we can think printing these kind of information as a table.

**Comment by edwardstjohn** [comment]
Of course, changed to a single printout at the start of the horizon view (hopefully the new commit is showing up on this pull request?)

**Comment by sertalpbilal** [comment]
Thanks! 🔥

**Pull request merged**
